### ISSUE TITLE
Icon reverses text

### ISSUE THREAD

**Issue by AckslD** [SmiteshP/nvim-gps#52]
I'm not sure what's going on and if it's `nvim-gps`'s fault but when I set the `container` icon to the one I want it reverses the whole text, see following screenshot for what I mean:

![gscreenshot_2021-12-20-094442](https://user-images.githubusercontent.com/23341710/146738673-f7a214b6-53f5-4587-baa4-43fc72f8f45f.png)

If I set it to eg `'c'` it's not reversed. It is also reversed if I just print `require('nvim-gps').get_location()`. Any idea what's going on here? The icon I want to use is `0xfb85` (ﮅ). I'm using [nerd-fonts-fira-code](https://aur.archlinux.org/packages/nerd-fonts-fira-code/) from AUR and alactritty.

Edit: If I use another one, eg `0xf01c` it's not reversed.

**Comment by SmiteshP** [comment]
I am not able to reproduce this issue in my config. I am using alacritty and Input Mono font. Also tried it with the AUR fira code font you mentioned, still works fine for me.
So something else in your config must be reversing the text.

**Comment by AckslD** [comment]
Thanks for checking @SmiteshP, I'll let you know if I figure out why this happens :)

**Comment by jdrouhard** [comment]
The problem is that some icons in nerdfonts switch the active direction for the bidirectional algorithm. I described [this issue](https://github.com/kyazdani42/nvim-web-devicons/issues/80) in nvim-web-devicons which has the same issue for some filetype icons (tex and svg are ones I know of for certain).

If you surround the icon with the direction isolates like I describe there, it should fix your issue.

**Comment by AckslD** [comment]
I see thanks for explaining @jdrouhard!
