### ISSUE TITLE
Better support for C++ methods written outside class

### ISSUE THREAD

**Issue by tom-anders** [SmiteshP/nvim-gps#8]
If I have 

``` 
class C {
   void foo();
}
void C::foo() {}
```
Then if my cursor is at the last line nvim-gps will just show the method `foo`. It would be very useful though if it also included the name of the class `C`. I tried adding this to the query via 

```
((function_definition
	declarator: (function_declarator
		declarator: (scoped_identifier
                    namespace: (namespace_identifier) @class-name
			name: (identifier) @method-name))) @scope-root)
```
But then it *just* shows the class but not the method name anymore. Looks like currently it doesn't allow for multiple captures in a single query.

**Comment by SmiteshP** [comment]
Yep, you are right! Right now only immedieatly next query can get captured. I had actually considered making a special capture group (inplace of scope-root) to retrieve next two captures for this specific case. However this was the only use case I found for it. And since the `get_location` function gets called at every cursor movement, I didn't want to add something that could it down.

**Comment by SmiteshP** [comment]
Hey @tom-anders
I just added this feature since it doesn't seem to slow down the performance. Let me know if its working ok!

**Comment by tom-anders** [comment]
Works great, thanks again!
