### ISSUE TITLE
[golang] location not calculated when curson on a commented

### ISSUE THREAD

**Issue by kassio** [SmiteshP/nvim-gps#96]
- Language: golang
- nvim version: NVIM v0.8.0-dev+1582-gc051ea83d
- nvim-gps commit: 9552418fcbb9587025f4bd38364259b3888f582b

---

I couldn't identify the root cause of this, but when the cursor is on a comment the location is not being shown in the statusline. (I suppose something with the query):

https://user-images.githubusercontent.com/120483/166646250-0153642a-292d-41c0-a0ff-d65629364779.mov

**Comment by SmiteshP** [comment]
Yep! I am aware of this issue, unfortunately this happens because treesitter does not treat comment nodes as child for the function node. Instead comment nodes kind of get their own tree, so when on a comment node we are unable to get info about the containing scope.

PS - I am currently working on a LSP based plugin to provide full breadcrumbs like functionality. It should be able to give context info like nvim-gps as well as let you jump around the file on functions, methods, variables, etc, etc. Using LSP will help be get rid of these inconsistencies of treesitter and another benefit is that I won't need to maintain anything for specific languages.
Will let you know when its ready to use :)
